services:
  - type: web
    name: flex-source
    plan: free
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: STRING_SESSION
        sync: false
    buildCommand: pip install -r requirements.txt
    startCommand: python3 modified.py
    env: python
