services:
  - type: web
    name: flex-source                                                                                   
    runtime: python-3.10.4  # جرب 3.9.x إذا استمرت المشكلة
    plan: free
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: STRING_SESSION
        sync: false
    buildCommand: pip install -r requirements.txt
    startCommand: python3 modified.py
    env: python
